# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: all-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Java Dev Kit
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version-file: .java-version
      - name: Build with Maven
        run: mvn -B -P all-tests verify --file pom.xml
